### ISSUE TITLE
vscode /usr/share/code/code --ms-enable-electron-run-as-node hardhat solidity consumes CPUs!

### ISSUE THREAD

**Issue by AuroraLantean** [NomicFoundation/hardhat-vscode#211] opened 2022-07-19 10:07 UTC
Somehow this plugin consume a lot of CPU time, and I do not know why.
At that time I was not running Hardhat test or developing on Hardhat or Solidity ...
As you see below the top 3 processes are running that plugin.
After disabling that plugin, my CPU activities have been reduced dramatically.
I am running on Linux Mint 20.3
![vscode3](https://user-images.githubusercontent.com/73493219/179725545-dfb17b3a-6c01-4bf2-87b3-0db40912d2fa.png)
please advise. thanks

**Comment by kanej** [comment] 2022-07-19 10:10
@AuroraLantean thanks for the feedback.

To clarify, do you mean that you had a hardhat project open, but where doing no editing on solidity files so why is the plugin consuming so much CPU?

**Comment by 0xMohandes** [comment] 2022-07-20 04:59
I am having the same issue with version 0.4.4. I didn't know why when I open vscode ( with a project) it just starts using high cpu and never ends ( without even touching anything). I started disabling all extensions until I found it's from Solidity+Hardhat extension. I downgraded it to 0.4.3 and the issue was resolved.
The changelog for new version (0.4.4) is showing this:

- Fix to restart validation processes on unexpected exits ([#209](https://github.com/NomicFoundation/hardhat-vscode/pull/209))

So I suppose it was trying to continue the process that was not completed before last exist. Interestingly there was no such condition for my project. so definitely this new fix has brought a new bug!

**Comment by danielattilasimon** [comment] 2022-07-20 06:39
Same here, constantly high CPU usage when the plugin is enabled and the workspace contains Solidity file(s). No issues when opening a workspace containing no Solidity.

It is turning my MacBook into a vacuum 😆

**Comment by kanej** [comment] 2022-07-20 08:27
Thanks for the reports. I suspect it is getting stuck in a loop while trying to load the hardhat config and restarting. I will put a fix together.

**Comment by kanej** [comment] 2022-07-21 13:51
@danielattilasimon, @AuroraLantean 

We have pushed a fix for high cpu in some cases (specifically a restart loop from bad hardhat configs), can you try version `0.4.5` and see if you still see high cpu?

**Comment by danielattilasimon** [comment] 2022-07-22 13:50
Thank you so much! The issue is fixed on my end 🙏

Interesting that it happens with bad configs. Maybe I should take a closer look at ours 😅

**Closed** 2022-08-02 14:09 UTC
