### ISSUE TITLE
release language server for coc.nvim users

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat-vscode#279] opened 2022-11-11 06:31 UTC
Hi, I tested hardhat-vscode language server in coc.nvim it has reference support, can it be released officially to npm so that coc.nvim users can start using it by adding the following config?

```
  "languageserver": {
    "solidity": {
      "command": "hardhat-language-server",
      "args": ["--stdio"],
      "rootPatterns": [".git/"],
      "trace.server": "verbose",
      "filetypes": ["solidity"]
    }
  },
```

**Comment by kanej** [comment] 2022-11-11 10:10
This is on our roadmap, with the intention to release a stand alone version of the language server in the next few months.

We want to restructure our repo to separate out the language server as a package, and split out our integration tests to support that; which are the current blockers.

**Comment by alannotnerd** [comment] 2022-11-18 10:17
I have ported it here (https://github.com/alannotnerd/solsp)

**Comment by alannotnerd** [comment] 2022-11-19 05:11
@kanej This is exactly the `server` subfolder in this repo.  The problem of the boot process is caused by `module-alias`. It seems not respect the `_moduleAliases` field in the package.json. Solved by register the aliases programmatically.

**Comment by kanej** [comment] 2022-11-24 09:24
I am closing this as a duplicate of #68. We are doing our initial investigations into getting the language server working with vim coc, and will write up our notes on that issue.

**Closed** 2022-12-01 11:39 UTC
Labels: enhancement
