### ISSUE TITLE
Show docstring when hovering on function

### ISSUE THREAD

**Issue by iFrostizz** [NomicFoundation/hardhat-vscode#617] opened 2024-11-24 12:44 UTC
When hovering over a function by the use of the [lua function on neovim](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.hover())
```lua
vim.lsp.buf.hover()
```
the modal box opens and works fine. Though, the docstring is not read as when using an LSP such as rust-analyzer. This feature would improve code understanding because there would be no need to go to definition to read the docstring.

![image](https://github.com/user-attachments/assets/297f7fbf-bc87-4558-8b28-103a4f00a424)

**Comment by kanej** [comment] 2024-11-25 11:56
This is something we definitely need. I am going to close this request as a duplicate of: https://github.com/NomicFoundation/hardhat-vscode/issues/268

**Closed by kanej** 2024-11-25 11:56 UTC
Labels: status:triaging

**Comment by iFrostizz** [comment] 2024-11-25 14:22
Sorry @kanej for the duplicate, Slang should be capable of this now right ? I'm happy to help with solving my issues if that can save you some time :)
