### ISSUE TITLE
 ENXIO: no such device or address, open '/dev/tty'

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat-vscode#469] opened 2023-04-27 01:34 UTC
After switching to @nomicfoundation/coc-solidity, I started to receive some errors like the following:

Hardhat project `<project_name>` is not able to initialize
ENXIO: no such device or address, open '/dev/tty'

Do you have an idea on what it is?

**Comment by kanej** [comment] 2023-04-27 11:15
Hey, @GopherJ, is the repo open source so we can try and reproduce?

Are there any elements of your hardhat config that depend on user input? Does hardhat cli show any errors for this?

**Comment by kanej** [comment] 2023-04-28 08:56
@GopherJ are you getting the error from the vscode extension or the hardhat cli or both?

**Comment by GopherJ** [comment] 2023-05-04 00:24
@kanej sorry for my late response, I got this error from hardhat-vscode's coc plugin

**Comment by antico5** [comment] 2023-05-18 12:53
When you run hardhat commands, do you get any prompt on the shell ? i.e. for some key of anything. Because this error happened before for a user that had a plugin that prompted for some password when running hardhat

**Comment by kanej** [comment] 2023-05-25 15:43
Hey @GopherJ, I am going to close this issue. Let us know if you are still experiencing a problem with coc on this repo.

**Closed by kanej** 2023-05-25 15:43 UTC
Labels: type:bug, status:needs-more-info

**Comment by GopherJ** [comment] 2023-09-30 06:24
@kanej I think this issue shouldn't be closed because if I uninstall coc-solidity it disapears

**Comment by GopherJ** [comment] 2023-09-30 06:25
> `cryptoenv`

no I don't have cryptoenv installed @antico5
