### ISSUE TITLE
Updating another function's visibility in another file does not update "Undeclared identifier" error

### ISSUE THREAD

**Issue by tnguyen42** [NomicFoundation/hardhat-vscode#283] opened 2022-11-20 17:02 UTC
Hello,
Here's a little bug I noticed when working with this extension I'm using to replace `solidity by Juan Blanco`.

### Configuration
VSCode version: 1.71.1
OS: MacOS 12.4
Extension version: v0.5.5

### Steps to reproduce
- Create a Solidity file with a private function in it
- Create another file, import the first file, inherit from the first file's smart contract, try to call the private function in it. As expected, the function is an "Undeclared identifier"
- Update the private function to make it internal: you would expect the error in the error file to go away, but it doesn't
- Reload VSCode to go the error effectively go away

Thank you for your work!

**Comment by kanej** [comment] 2022-11-21 11:15
Hey @tnguyen42, thanks for the steps, I have been able to reproduce the issue.

Our validation is working on the changed file and its dependents, but it is not re-validating anything that depended on the changed file.

**Comment by kanej** [comment] 2023-01-02 16:49
Closing as a duplicate of #95.

**Closed by kanej** 2023-01-02 16:49 UTC
Labels: type:bug, status:ready, priority:medium
