### ISSUE TITLE
No completion for special variables 

### ISSUE THREAD

**Issue by MonadeInFlask** [NomicFoundation/hardhat-vscode#406] opened 2023-02-23 14:55 UTC
It seems that the lsp don't provide completions for global variables such as msg, block. Can this feature be added？

**Comment by antico5** [comment] 2023-02-23 15:00
Thanks for your feedback! There's already an open issue for this: https://github.com/NomicFoundation/hardhat-vscode/issues/334. We'll address it as soon as possible :)

**Comment by antico5** [comment] 2023-02-23 15:01
Duplicate of #334

**Comment by MonadeInFlask** [comment] 2023-02-24 05:27
thank you.

**Comment by kanej** [comment] 2023-02-24 11:06
I am going to close this as a duplicate of #334.

**Closed by kanej** 2023-02-24 11:06 UTC
Labels: status:triaging
