### ISSUE TITLE
Linting doesn't work for @openzeppelin/contracts

### ISSUE THREAD

**Issue by daron4ever** [NomicFoundation/hardhat-vscode#290] opened 2022-11-25 00:42 UTC
Hi,

I worked with Solidity extension by Juan Blanco and worked perfectly well, but the import is not working since I moved to this extension. Otherwise, I should add it like this:
`import './node_modules/@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol';`

<img width="532" alt="Screen Shot 2022-11-25 at 8 33 31 AM" src="https://user-images.githubusercontent.com/18229512/203878761-4789e34c-a183-444d-897b-bda55e745762.png">

**Comment by kanej** [comment] 2022-11-25 09:26
Hey @daron4ever, what is the error when you hover over the red line?

**Comment by daron4ever** [comment] 2022-11-25 19:33
> Hey @daron4ever, what is the error when you hover over the red line?

Source "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol" not found: File not found. Searched the following locations: "".solidity(6275)

**Comment by kanej** [comment] 2022-11-28 09:34
@daron4ever is the file you are importing from within a Hardhat project with openzeppelin installed through npm?

**Comment by daron4ever** [comment] 2022-11-29 11:50
> @daron4ever is the file you are importing from within a Hardhat project with openzeppelin installed through npm?

yes. but I have not set a hardhat project yet.

**Comment by kanej** [comment] 2022-11-29 15:39
Our import functionality depends on the sort of project that the contract is in.

If we detect a `hardhat.config.{ts,js}` we know the project is a hardhat project and include `node_modules` when resolving direct imports like `@openzeppelin/...`.

In a Foundry project the extension leverages the `remappings.txt`.

A contract file outside of a project only supports relative paths.

Solc leaves import resolution to the development framework, if we can't determine the development framework or there is no framework, we can't apply the appropriate rule for import resultion.

https://docs.soliditylang.org/en/latest/path-resolution.html

**Comment by maguroid** [comment] 2022-12-01 13:28
Hey @kanej, I have the same error with importing. My project structure is like this.
https://github.com/InsureDAO/pool-contracts

I have test contracts in `test/foundry/*`, and use `remappings.txt` to map a library's path. But that does not work.
What is the proper solution for the foundry test contract?

**Comment by antico5** [comment] 2022-12-01 15:47
@maguroid The problem is your project doens't have a foundry.toml file on the root. Then we can't tell that contracts under `test` are meant to be compiled with foundry, and treat them as standalone solidity files (which don't have remapping support, just relative imports). @daron4ever please try this solution as well. Create an empty foundry.toml file on your project root.

**Comment by CodeWarriorr** [comment] 2022-12-06 13:31
I have exactly the same problem. 
This problem appeared after update to `0.6.X`, the error is not present in `0.5.5` version, but still doesn't seem to work perfectly.
I have `hardhat.config.ts` and I've installed @openzeppelin through npm

**Comment by CodeWarriorr** [comment] 2022-12-07 09:07
@kanej Unfortunately its not open source, at least yet. 
This is getting stranger, I've copied all the files to newly set hardhat ts project and everything seems to be working again. 
Is there any way to reset cache or something for the workspace and/or the extension ?

**Comment by kanej** [comment] 2022-12-07 10:33
@CodeWarriorr the extension doesn't maintain longterm state, so closing and opening vscode on teh project would wipe it.
However we do leverage some hardhat caches. You can clear those with `npx hardhat clean`.

**Comment by CodeWarriorr** [comment] 2022-12-08 13:50
Thanks.. I'm not sure if clean helps, I was able to get around this (for now at least) by renaming contract files back and forth

**Comment by maguroid** [comment] 2022-12-13 23:19
@kanej @antico5 
> Create an empty foundry.toml file on your project root

It works fine. Thanks!

**Closed** 2022-12-23 13:59 UTC
