### ISSUE TITLE
Autocompletion for npm imports not working

### ISSUE THREAD

**Issue by FreezyEx** [NomicFoundation/hardhat-vscode#116] opened 2022-03-15 20:43 UTC
Autocompletion as shown here is not working

https://twitter.com/i/status/1501981617304309760

![image](https://user-images.githubusercontent.com/14966614/158469024-803ecc1b-63c5-480a-8067-f10123f2bf17.png)

**Comment by kanej** [comment] 2022-03-16 09:19
Thanks for the feedback. First can I confirm what OS your running on?

I suspect the issue is that there is no closing `"` in the example above. We determine whether we are in an import statement by parsing the line. But our parser can misreport if there is no closing bracket:

![Mar-16-2022 09-15-04](https://user-images.githubusercontent.com/24030/158556902-bdd7e063-7fef-4994-9157-a5566bcc0fa6.gif)

@FreezyEx can you confirm you can completions if you start with `import "<cursor here>";`?

This is a limitation, but improvements mean rework in [solidity-parser](https://github.com/solidity-parser/parser), making this quite a big task.

**Comment by FreezyEx** [comment] 2022-03-16 10:25
I just tried adding the closing` "` but same issue:
![image](https://user-images.githubusercontent.com/14966614/158569366-38606d2f-4edc-4b4c-b988-bea0f32a26f7.png)

I am on Windows10

**Comment by kanej** [comment] 2022-03-16 11:18
@FreezyEx can I confirm two things:

* the completion requires a trigger, it doesn't happen on every character. So if the cursor is after z in `@openz` and you hit `ctrl + space`, or if you type `@openzeppelin` then `/` do you get any completion?
* are you able to navigate to openzepplin files, for instance the `"@openzeppelin/contracts/access/Ownable.sol"` in the import bellow if you right click on `Ownable.sol` and choose go to definition?

**Comment by FreezyEx** [comment] 2022-03-16 11:25
> * the completion requires a trigger, it doesn't happen on every character. So if the cursor is after z in @openz and you hit ctrl + space, or if you type @openzeppelin then / do you get any completion?

No, I don't get any completion.

> * are you able to navigate to openzepplin files, for instance the `"@openzeppelin/contracts/access/Ownable.sol"` in the import bellow if you right click on `Ownable.sol` and choose go to definition?

Yes it correctly goes to the `Ownable.sol`

**Comment by kanej** [comment] 2022-03-16 11:31
Are there any errors in the output channel immediately after attempting an import completion on the line in question. You can find the output channel by going to the output tab and picking hardhat from the dropdown:

![image](https://user-images.githubusercontent.com/24030/158580726-45e5c17a-ef01-4757-8d0f-e2318117c7f9.png)

**Comment by FreezyEx** [comment] 2022-03-16 11:38
I just tried with another project and now seems to work. I don't understand which was the issue. Both are hardhat projects.
Now I have the autocompoletion after `openzeppelin/`

**Closed** 2022-03-16 11:46 UTC

**Comment by kanej** [comment] 2022-03-16 11:51
@FreezyEx that is a known bug, https://github.com/NomicFoundation/hardhat-vscode/issues/91#issue-1161216370.

Sorry it took so many iterations to get there, I will lead with that next time. Thanks for helping work that through.

**Comment by FreezyEx** [comment] 2022-03-16 12:08
Thank you for the help @kanej
